spring.config.import=optional:file:./local.properties
spring.application.name=DoItLater

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}